### ISSUE TITLE
Allow filtering settings

### ISSUE THREAD

**Issue by mgmeyers** [mgmeyers/obsidian-style-settings#10]

**Comment by firinael** [comment]
@mgmeyers is this something easy to implement? I could try this out as a way to learn plugins, if you'd like the help.

Also it'd be cool if you added tags like `help wanted` to issues that could use another hand.

**Comment by mgmeyers** [comment]
@firinael I'd be happy to receive help on any issues! This issue is pretty complex, though. I was thinking about rebuilding the UI using svelte to make it easier to dynamically filter settings.

**Comment by claremacrae** [comment]
Thank you for a really useful plugin!

I came here to submit a request for this - It would be a great help, especially as every time one goes back to the plugin settings, the tree of options has been collapsed again, so with any style with more than a small number of settings, that one is not yet familiar with, it gets a bit painful experimenting with the settings fairly quickly...
