### ISSUE TITLE
Some Plugins and Theme don't show after v. 1.0.0 Update

### ISSUE THREAD

**Issue by Liong1976** [mgmeyers/obsidian-style-settings#103]
After the v. 1.0.0 some plugins and my themes don't show in the Style Setting View.

The themes that I have are Minimal and Shimmering Focus. The plugin that doesn't show is Supercharged Links.

Here is the screenshot

![image](https://user-images.githubusercontent.com/88898230/216366330-ed76db74-cd40-410f-90e6-8fb54a7939a3.png)

Here is the console screenshot

![image](https://user-images.githubusercontent.com/88898230/216366619-c48de3e4-3a81-4584-85c1-6b0dcf896cb6.png)

I am on Windows, Obsidian version 1.1.12, installer 1.1.9

**Comment by TonyAtlas** [comment]
I have the same problem.

Before the update, my list of plugins looked like this:

![Pic_20230202_204311](https://user-images.githubusercontent.com/82872888/216402169-33492e5a-cd27-4dd6-9eb6-c28f2a8dfce4.jpg)

And now this:

![Pic_20230202_204855](https://user-images.githubusercontent.com/82872888/216402406-8da90c6a-b667-432e-aad9-4cf9ec57a4c3.jpg)

So there is only one plugin left.

 Windows, Obsidian version 1.1.9, installer 1.1.9

**Comment by mgmeyers** [comment]
@mProjectsCode Any thoughts on what might be causing this?

**Comment by mProjectsCode** [comment]
Probably some weird heading levels. I will take a look at it shortly.

It would be nice if the error can be narrowed down to specific plugins/themes.

**Comment by mProjectsCode** [comment]
> It would be nice if the error can be narrowed down to specific plugins/themes.

Floating TOC seems to be one of the plugins causing this bug.

**Comment by mProjectsCode** [comment]
Found the bug. In the Floating TOC plugin, the headings are not in descending order. 
The heading structure is `2, 3, 3, 2, 2, 3, 1` and that caused problems for the component tree builder.
