### ISSUE TITLE
Syntax highlighting for punctuation not functioning

### ISSUE THREAD

**Issue by owenviva** [mgmeyers/obsidian-style-settings#106]
Although I have set the syntax highlighting to a specific color. The punctuation I typed in code block is still colored as code text without highlighting. 
Setting for punctuation:
<img width="743" alt="Punctuation Setup" src="https://user-images.githubusercontent.com/124546405/217083763-82fc27d8-0f7c-4e32-ab80-807acd49b331.png">
Punctuation example in code block:
<img width="530" alt="Punctuation Example" src="https://user-images.githubusercontent.com/124546405/217083720-bc7927e6-033d-45d0-87eb-0b6ad716721d.png">

**Comment by mgmeyers** [comment]
Hi @owenviva This looks like an issue with the theme you are using. Please report the issue in the theme's repository.
