### ISSUE TITLE
Console Error: Component for proper lifecycle management is missing.

### ISSUE THREAD

**Issue by damiankorcz** [mgmeyers/obsidian-style-settings#123]
I've recently noticed this Error come up when you enable my theme (Prism) using Style Settings. Not sure if it's something I'm doing wrong or not. Here is a log of the error:
[obsidian.md-1684923967441.log](https://github.com/mgmeyers/obsidian-style-settings/files/11553430/obsidian.md-1684923967441.log)

**Comment by mgmeyers** [comment]
This should be fixed now @damiankorcz. This required a significant rewrite. Let me know if you run into any bugs.

**Comment by damiankorcz** [comment]
Hey @mgmeyers, something is not quite right. The Style Settings classes don't seem to get attached to the Body at all when you launch Obsidian. I haven't yet narrowed down how to get around it. No errors/warnings in console.

**Comment by mgmeyers** [comment]
Thanks @damiankorcz. I think I figured out what was going on. Update and see if you still have issues.

**Comment by damiankorcz** [comment]
I think it's all good now! Also I think you might have addressed issue #89 as far as I can tell. Thanks!
