### ISSUE TITLE
No Color Override for Maroon

### ISSUE THREAD

**Issue by NytSong** [mgmeyers/obsidian-style-settings#132]
Going through customizing my colors today to make them a little bolder and noticed that there is no option to override Maroon.  I am using the most up to date version.

![image](https://github.com/mgmeyers/obsidian-style-settings/assets/61587778/4be4906d-28ee-4dba-ae85-868597ce3c31)

**Comment by mgmeyers** [comment]
Hi @NytSong, this looks like an issue with the theme and not style settings. You'll need to open an issue in the theme's repository to get help with this.

**Comment by NytSong** [comment]
How is it the theme when this is within the settings for Style Settings?

**Comment by mgmeyers** [comment]
Theme developers control and configure which settings appear in style settings. From your screenshot it looks like the theme developer forgot to add a setting under color overrides for maroon.

**Comment by NytSong** [comment]
Ok, then I apologize for bugging you on it.  I literally just started setting Obsidian this week and am attempting to find my way through it.  Thank you.
