### ISSUE TITLE
where folder in my desktop I should add file css?

### ISSUE THREAD

**Issue by AndresProgramerCOP** [mgmeyers/obsidian-style-settings#135]
I don't know where  I would put the file stylesheet

**Comment by KuroChu** [comment]
As stated in [Obidian Help](https://help.obsidian.md/) to extend Obsidian with custom [CSS snippets](https://help.obsidian.md/Extending+Obsidian/CSS+snippets) u can create new css files in
`%vault_name%/.obsidian/snippets/SOME_NAME.css`
and list the snippets under **Options>Appearance>CSS snippets** in the settings
