### ISSUE TITLE
Tooltip on hover

### ISSUE THREAD

**Issue by chetachiezikeuzor** [mgmeyers/obsidian-style-settings#14]
ʕ•́ᴥ•̀ʔっ Hello!!! Would it be possible to get a tooltip to show when hovering over a slider in Style Settings? (My mouse is hovering over the sliders in both images btw). 
<img width="973" alt="Screen Shot 2021-07-02 at 3 36 06 PM" src="https://user-images.githubusercontent.com/79069364/124326369-d7885b80-db4b-11eb-8c0f-33806b9f4821.png">
<img width="975" alt="Screen Shot 2021-07-02 at 3 35 56 PM" src="https://user-images.githubusercontent.com/79069364/124326371-d9521f00-db4b-11eb-82cc-4af9c337602f.png">

**Comment by mgmeyers** [comment]
@chetachiezikeuzor Added to v0.2.6! Let me know if you have any issues with it.

**Comment by chetachiezikeuzor** [comment]
It works perfectly! Thank you 🤗
