### ISSUE TITLE
Bug: Toggle command adds three empty lines before frontmatter YAML

### ISSUE THREAD

**Issue by kometenstaub** [mgmeyers/obsidian-style-settings#152]
When using the "Toggle between reduced and max image size" command defined by Shimmering Focus (cc @chrisgrieser), three empty lines are prepended to the document, rendering frontmatter YAML unusable.

When no YAML is present, only one line is prepended to the note.

cc @mProjectsCode, I think you initially PRed that feature? 

Obsidian version: 1.5.10
Installer version 1.5.6
Style Settings: 1.0.7

This issue also happens in the sandbox with just Style Settings and Shimmering Focus installed.

<img width="543" alt="image" src="https://github.com/mgmeyers/obsidian-style-settings/assets/83140328/fd80fe72-c434-468c-bad9-86e45b31d9b2">

<img width="667" alt="image" src="https://github.com/mgmeyers/obsidian-style-settings/assets/83140328/5cfa0ba1-4259-4db4-85a2-a4434e1722b8">

**Comment by mProjectsCode** [comment]
It seems like [this commit](https://github.com/mgmeyers/obsidian-style-settings/commit/7805ab40555db7b3a80403b733763563ad1e4ed2#diff-e0306954f0632d49ed727e45b5d182218e1b97df0138a8e4e7e7f4fecb36989c) broke the toggle command and causes the error that you are seeing in the console. No idea why it modifies the document though.

**Comment by kometenstaub** [comment]
Thank you! ❤️
