### ISSUE TITLE
Allow variable-select to change body class

### ISSUE THREAD

**Issue by kepano** [mgmeyers/obsidian-style-settings#16]
This would work similarly to `variable-toggle` except allow you to switch between 3 or more different values that are not compatible with each other.

**Comment by kepano** [comment]
My use case for this, is allowing users to change between Minimal's 4 light theme options and 3 dark theme options

**Comment by mgmeyers** [comment]
@kepano This can be done now using `class-multi-toggle`: https://github.com/mgmeyers/obsidian-style-settings#class-multi-toggle

**Comment by kepano** [comment]
Very cool, thanks!

**Comment by Dr-Octopus-dev** [comment]
> [@kepano](https://github.com/kepano) This can be done now using `class-multi-toggle`: https://github.com/mgmeyers/obsidian-style-settings#class-multi-toggle

It seems that there is no chapter called class-multi-toggle in README

**Comment by Dr-Octopus-dev** [comment]
> [@kepano](https://github.com/kepano) This can be done now using `class-multi-toggle`: https://github.com/mgmeyers/obsidian-style-settings#class-multi-toggle

It seems that there is no section called class-multi-toggle in README
