### ISSUE TITLE
Percentages as format

### ISSUE THREAD

**Issue by Erallie** [mgmeyers/obsidian-style-settings#171]
I am developing a theme, and I would like to integrate compatibility with Style Settings, but I'm having difficulties with `variable-number-slider`.

I cannot use percentages ( % ) as the `format`, otherwise it displays the following error in the settings panel: 
<img width="538" alt="Screenshot 2024-08-28 at 12 25 02 PM" src="https://github.com/user-attachments/assets/4efea064-4b46-443e-ac4e-6628beafba14">

No errors seem to show up in the developer console.

**Comment by mgmeyers** [comment]
Hi @Erallie , does it work if you wrap the `%` sign in quotes?

**Comment by Erallie** [comment]
> Hi @Erallie , does it work if you wrap the `%` sign in quotes?

It gets rid of the issue, but when I use the variable in my css—in this case, the background color—using the variable in my css makes the background malfunction, or otherwise completely disappear:

<img width="868" alt="Screenshot 2024-08-28 at 12 34 15 PM" src="https://github.com/user-attachments/assets/4857a0a1-9823-4038-9afa-4a614bbafa7f">

This is the code I'm using it in:

```
    --background-primary: hsl(var(--accent-h), 35%, calc(var(--bg-l-modifier) + 25%));
```

**Comment by Erallie** [comment]
Sorry, when I said "it gets rid of the issue", I meant it gets rid of the error. But there's still an issue, since it's not usable like the other variables.

**Comment by Erallie** [comment]
@mgmeyers sorry forgot to @ you.

**Comment by mgmeyers** [comment]
Hmm, if you look at the source for a style tag with `css-settings-manager` what is `--bg-l-modifier` being set to?

<img width="931" alt="Screenshot 2024-08-28 at 1 20 01 PM" src="https://github.com/user-attachments/assets/2036040b-2196-4da7-bc85-331407703574">

**Comment by Erallie** [comment]
@mgmeyers They're both empty
<img width="442" alt="Screenshot 2024-08-28 at 1 23 40 PM" src="https://github.com/user-attachments/assets/1752d56e-693b-40b0-a1b2-f1b31acf7de7">

**Comment by Erallie** [comment]
oh wait I think I misunderstood what you said. Let me check the elements, not the classes.

**Comment by Erallie** [comment]
@mgmeyers Sorry, I misunderstood what you said. It doesn't set `--bg-l-modifier`:

<img width="437" alt="Screenshot 2024-08-28 at 1 26 50 PM" src="https://github.com/user-attachments/assets/79ad32a6-6d1e-4d3c-a8ae-036bc8ff2866">

**Comment by Erallie** [comment]
oh wait I still showed the wrong thing... sorry for so many pings...

**Comment by Erallie** [comment]
@mgmeyers Sorry for yet another ping. This time I think I *actually* found the *actual* thing you were looking for:

<img width="436" alt="Screenshot 2024-08-28 at 1 32 43 PM" src="https://github.com/user-attachments/assets/909a22cf-0af7-4df8-b7cf-07ad58642c8b">

Nothing is set.

**Comment by mgmeyers** [comment]
Ah, right. The value will only show up there if it's been changed in Style Settings. If you haven't, you'll also want to set a default value in your theme's CSS file so that `calc` doesn't break. Eg, `--bg-l-modifier: 0%;`

**Comment by Erallie** [comment]
@mgmeyers Oh yes that fixed it! Thank you!! :heart:

**Comment by mgmeyers** [comment]
Great, glad we figured it out!
