### ISSUE TITLE
If a label is provided for class-select default should use the label text 

### ISSUE THREAD

**Issue by kepano** [mgmeyers/obsidian-style-settings#18]
If a label is provided for `class-select` the description default should use the label text.

The description text shows that default is `minimal-light` but the dropdown is labeled `Default`. This could be confusing to users.

Example:
<img width="770" alt="Screen Shot 2021-08-06 at 21 07 52" src="https://user-images.githubusercontent.com/10565871/128587413-343a6c16-7849-4ffb-93e1-ab0938d1afcd.png">

**Comment by mgmeyers** [comment]
This should be fixed now!
