### ISSUE TITLE
Headings move to the right, instead of center

### ISSUE THREAD

**Issue by psychsatani** [mgmeyers/obsidian-style-settings#20]
In the ITS theme, the option to centre the headings with lines on either side puts the heading on the right instead of centre. Would really like this option to work, a solution to this bug will be much appreciated. I have attached the video that shows this. I am on 0.12.13 insider build. 

https://user-images.githubusercontent.com/78266798/128644023-a2d170a2-bff3-4ddc-a004-09ce10e6a2b9.mov

**Comment by mgmeyers** [comment]
@psychsatani I recommend filing this as an issue here, as I don't believe this is a bug with the plugin: https://github.com/SlRvb/Obsidian--ITS-Theme/issues

**Comment by psychsatani** [comment]
@mgmeyers I just fixed it by unchecking the "hide header underline" option. It was checked when I produced the error. I have updated this on the theme page too. Thank you!

<img width="801" alt="image" src="https://user-images.githubusercontent.com/78266798/128795600-85f07ddc-9395-4151-a75d-e857b1a9f234.png">
