### ISSUE TITLE
HSL Split issue with pure white and pure black values (including shades inbetween)

### ISSUE THREAD

**Issue by damiankorcz** [mgmeyers/obsidian-style-settings#29]
Hi @mgmeyers,
I've encountered an issue with the HSL Split when selecting pure white and pure black values (including shades in between). The Hue returns NaN making it unusable. It's quite strange since choosing anything that only just increases the Saturation fixes the Hue value. I'm unsure if this could be fixed by clamping the values or something along those lines.

Example for pure white: 
![image](https://user-images.githubusercontent.com/7290097/136674187-0439e7b6-4c39-4e4b-8ec7-08db0a20e331.png)
![image](https://user-images.githubusercontent.com/7290097/136674212-f377313c-5e10-4ec6-8ae4-62200727b676.png)

Example for pure black:
![image](https://user-images.githubusercontent.com/7290097/136674225-55101a4c-66d6-4fc5-9eee-ad39a21a4329.png)
![image](https://user-images.githubusercontent.com/7290097/136674229-d139c5de-65c9-4a12-a1fa-f14774bc7802.png)

**Comment by mgmeyers** [comment]
This should be fixed now @damiankorcz. Let me know if you still run into issues with it.

**Comment by damiankorcz** [comment]
> This should be fixed now @damiankorcz. Let me know if you still run into issues with it.

Seems to be all good now. Thank you for addressing this!
