### ISSUE TITLE
[Bug] Graph view won't change until reload

### ISSUE THREAD

**Issue by Mara-Li** [mgmeyers/obsidian-style-settings#38]
I wrote a snippet to change graph view with Style settings, but I don't seem to work without reload.

I have this in console : 
![image](https://user-images.githubusercontent.com/30244939/139804894-36d16001-4705-44f7-b040-bad4c37219cc.png)

Here is the snippet : https://gist.github.com/Mara-Li/bbda99650f3db6a5f5068309f6806fa8

**Comment by mgmeyers** [comment]
Hi @Mara-Li, this is unfortunately a limitation of how the graph is rendered. It picks up the CSS color values the first time it runs, and won't update after that. This is because the graph isn't rendered as HTML/CSS, but using `canvas`.

**Comment by Mara-Li** [comment]
Good to know in this case :)
