### ISSUE TITLE
[Bug] Can't resize body font

### ISSUE THREAD

**Issue by jokysatria** [mgmeyers/obsidian-style-settings#4]
![rX8dA1smtM](https://user-images.githubusercontent.com/69371378/113542761-238c3880-960f-11eb-80a6-e8bbd9d50958.gif)

The font size remains same even after I change it. Or do I miss something?

**Comment by mgmeyers** [comment]
Thanks @jokysatria ! This was a bug in https://github.com/mgmeyers/obsidian-california-coast-theme 

If you update the theme, it should work now!
