### ISSUE TITLE
How do I adjust the spacing above the unordered list?

### ISSUE THREAD

**Issue by zhl111** [mgmeyers/obsidian-style-settings#42]
![image](https://user-images.githubusercontent.com/29135984/145747814-9ac188af-b1af-4723-ae9a-86dc6cd651e0.png)

**Comment by zhl111** [comment]
The spacing after block references to new files is too large in preview mode, how can I adjust it?
![image](https://user-images.githubusercontent.com/29135984/145975094-5e961666-677d-48e2-804d-6f62527160cc.png)

**Comment by mgmeyers** [comment]
Hi there @zhl111 this seems like a question for the developer of your theme or the appearance channel in obsidian's discord. This plugin won't change the spacing here unless a theme developer sets it up to do so.

**Comment by zhl111** [comment]
I used California Coast
