### ISSUE TITLE
BUG: sidebar duplicates

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-style-settings#43]
<img width="390" alt="Screenshot 2021-12-14 22 56 45" src="https://user-images.githubusercontent.com/73286100/146085935-38788408-86d9-417b-bbfa-05ad4987f84f.png">

**Comment by mgmeyers** [comment]
Ah, yikes. Were you doing anything in particular when this happened @chrisgrieser ?

**Comment by mgmeyers** [comment]
Oh, nvm, I was able to repro.

**Comment by mgmeyers** [comment]
@chrisgrieser Can you install the latest version of the plugin and try again? I'm pretty sure I figured out what was causing this.

**Comment by chrisgrieser** [comment]
yep, seems to work now!
