### ISSUE TITLE
FR: Add new types: info-text, link, & donations

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-style-settings#44]
I think there are some "setting"-types that would be super useful to have:
1. simply info text. right now, the only "non-setting" you can add are headings. But sometimes, I want to add explanations for certain settings, that don't make sense in a heading or in the description of a certain setting. 
2. Also, being able to enter a link would be awesome. For example: Link to a section of the readme where one can find further info / screenshots. Or a link to a CSS snippet. (an option could also be to add linking capability to the info-text type above.)
3. Many plugins add a Donation button to their settings page, which is a nice and unobtrusive place for that. How about providing themes the a method for doing the same?

**Comment by damiankorcz** [comment]
Very much in support of all 3 features. I would love to have the ability to add links especially since I'm hoping to make a descriptive WIki page for the theme and linking directly to a page on the Wiki in different sections within Style Settings would be very convenient.
