### ISSUE TITLE
Potential Bug: Style Settings open in a pane pre-loads Color Pickers at the end of the Body

### ISSUE THREAD

**Issue by damiankorcz** [mgmeyers/obsidian-style-settings#48]
Noticed this recently and was curious if this is an intentional behaviour. No real harm with it all there. Just curious.
![image](https://user-images.githubusercontent.com/7290097/148314066-b74ed0cb-514b-4e97-95b9-801cc2178d6f.png)

**Comment by mgmeyers** [comment]
Hey @damiankorcz, yeah, this is intended behavior. The color pickers are added to the body like this so the color picker popup is positioned correctly on the page when it opens.

**Comment by damiankorcz** [comment]
Got it! In this case I'll close this issue. Thanks for the reply.
