### ISSUE TITLE
Style setting shows no style setting found

### ISSUE THREAD

**Issue by Smoonster** [mgmeyers/obsidian-style-settings#49]
<img width="1154" alt="Screenshot 2022-01-08 at 4 15 40 PM" src="https://user-images.githubusercontent.com/91936275/148641364-0b009e71-488a-43f8-90e7-c01cbfd449c3.png">

Hi,

I want to make some changes to the current style but I am getting this message. Kindly suggest what needs to be done.

**Comment by pcause** [comment]
same for me.  I just installed blue topaz theme which says it works with styles and it finds nothing

**Comment by Smoonster** [comment]
Whom should we write to? We don't seem to be getting response here.

**Comment by pcause** [comment]
I reinstalled the plugin and restarted obsidian and it worked!  thanks

**Comment by pcause** [comment]
I don't think we need to reach out.  It all worked once I reinstalled and restarted.  it works must have been something else.

**Comment by Smoonster** [comment]
Tried and it didnt work for me.

**Comment by mgmeyers** [comment]
@Smoonster It looks like you're using the default theme, have you activated a CSS snippet with a style settings configuration? For example, you can put this one in your CSS snippets folder (see `settings > appearance > CSS snippets`) and styles settings will pick it up: https://github.com/mgmeyers/obsidian-style-settings/blob/main/obsidian-default-theme.css

**Comment by depascalis** [comment]
@mgmeyers I believe the confusion is because of this line in the docs https://github.com/mgmeyers/obsidian-style-settings/blob/747e6dae575c4658379f962128213a322ec28bec/README.md?plain=1#L9
It should be more precise and point to `vault\.obsidian\snippets` or else one would put it in the vault root, like I did 😎

**Comment by KT9000** [comment]
@depascalis I think it should be copied into `vault\.obsidian\themes` instead of `vault\.obsidian\snippets` (and then also activated inside Obsidian as a theme named after the file, i.e. "obsidian-default-theme"). At least that's how I got it working.

> @mgmeyers I believe the confusion is because of this line in the docs
> 
> https://github.com/mgmeyers/obsidian-style-settings/blob/747e6dae575c4658379f962128213a322ec28bec/README.md?plain=1#L9
> 
> 
> It should be more precise and point to `vault\.obsidian\snippets` or else one would put it in the vault root, like I did 😎

**Comment by ZPCZPCZPC123** [comment]
你好，是否是使用了默认的主题，没有下载其他的主题，如blue topaz主题。
<img width="827" alt="屏幕截图 2024-12-23 181433" src="https://github.com/user-attachments/assets/05b2c027-5ba4-4477-9f58-32f08f40195b" />



![coac10aw](https://github.com/user-attachments/assets/b4f37ec0-39f0-4d78-b6c3-779bd122b009)
