### ISSUE TITLE
Accent color not translated correctly in the UI

### ISSUE THREAD

**Issue by icebruce** [mgmeyers/obsidian-style-settings#55]
Steps to reproduce

1. Set the Accent color from the Style settings -> #2168AB
2. Navigate Obsidian menu or create a link on a page
3. The accent color does not have the same shade (shows darker color)

![image](https://user-images.githubusercontent.com/66655064/152074340-576eae77-be82-46dd-ab59-1311eaf658c1.png)
![image](https://user-images.githubusercontent.com/66655064/152074397-a09f7814-eec3-4b3a-9175-e9e08b5eb473.png)

Notes:
- Latest version of Minimal, Minimal Style settings and Style settings installed
- Tried each style setting separately. Issue persists only when Style setting is enabled with an Accent color

**Comment by mgmeyers** [comment]
@icebruce This looks like an issue with the Minimal Theme. It seems it dims the "interactive accent" color in dark mode. You might try opening an issue there.

**Comment by icebruce** [comment]
@mgmeyers I think you are right. I switched to a different theme and the issue was not there. Thanks for the input, ill open a ticket for the Minimal Theme
