### ISSUE TITLE
Body font size setting not working?

### ISSUE THREAD

**Issue by lkhphuc** [mgmeyers/obsidian-style-settings#6]
Changing body font size does not have any effect on both edit and preview mode. 
Other values such as font line height right below take effect immediately.

I'm using California Coast theme by the way.

**Comment by mgmeyers** [comment]
Hi @lkhphuc! Try updating the theme. Another user reported this issue (https://github.com/mgmeyers/obsidian-style-settings/issues/4) and I made some changes earlier today. Let me know if you still have issues after updating.

**Comment by lkhphuc** [comment]
Hi, I've tried updated everything, plugin, theme, restart Obsidian but still cannot change the font size. I'm on MacOS by the way.

**Comment by lkhphuc** [comment]
Oh wait it's working now. Not sure why. Thank you.
