### ISSUE TITLE
[Feature Request] Indentation Guides Adjust

### ISSUE THREAD

**Issue by Johnson0907** [mgmeyers/obsidian-style-settings#65]
After v0.14.0, obsidian has built-in indentation guides, but the location of the indentation guides is not accurate.
Could you add settings of built-in indentation guides adjust?
For example:
- live preview
	- unordered list: n px
	- ordered list: n px
- reading view
	- unordered list: n px
	- ordered list: n px

**Comment by damiankorcz** [comment]
@Johnson0907 Style Settings serves as a framework for theme developers to specify settings that display in Style Settings from their Theme's CSS. It doesn't give the end user any settings by default. It's entirely up to the theme dev. If you wish to make customisations such as the ones you describe you should suggest this to your Theme creator or create a snippet that does it.

**Comment by Johnson0907** [comment]
Thank you.
