### ISSUE TITLE
The modified color of the tag has no effect.

### ISSUE THREAD

**Issue by ssmmtt** [mgmeyers/obsidian-style-settings#69]
![image](https://user-images.githubusercontent.com/16244320/174310572-fb541581-6e7f-4598-a1db-6ebf5d9df083.png)
![image](https://user-images.githubusercontent.com/16244320/174310610-c6a67f00-9f31-40c5-ab31-5093a5442574.png)
![image](https://user-images.githubusercontent.com/16244320/174310701-c8d58443-b514-4b98-a580-c51184a3b870.png)

**Comment by mgmeyers** [comment]
This seems like an issue with your theme. Please open an issue in the theme's repository rather than here
