### ISSUE TITLE
Style Settings is rendering weird for me.  Just started today 7-13. 

### ISSUE THREAD

**Issue by deehtodd** [mgmeyers/obsidian-style-settings#71]
The whole things is rendering weird and sections won't collapse. Here is a partial screen shot. 
![image](https://user-images.githubusercontent.com/77208255/178843014-1b751d36-9807-48a5-b74e-66a7f3c5cef9.png)

**Comment by kaosine** [comment]
Yeah I don't know about it rendering exactly like that, but it's not allowing me to collapse either.  I'm wondering if it's some issue w/v1.x? I'm on v1.1.9

**Comment by mgmeyers** [comment]
These are likely theme related issues. Please report them to your theme's author for help.
