### ISSUE TITLE
Spacing / Paragraphs, Headers

### ISSUE THREAD

**Issue by rk-kontur** [mgmeyers/obsidian-style-settings#73]
Hi there,
first of all: THANK YOU SO MUCH for this wonderful plugin. It so much eases daily use of Obsidian by the numerous layout options it presents. FANTASTIC WORK!!!!

I wondered for a few times, what could be a possible solution for my only little grief: I would very much like to adjust the spacing between paragraphs and also how much space is given after other items such as header,s, block quotes and codeblocks. This would make reading and writing so much easier for me.

Maybe I just overlooked a setting that is there. In that case, I apologize and thank you in advance for maybe pointing me in the right direction.

All the best. And: THANKS again!

**Comment by mgmeyers** [comment]
@rk-kontur Thank you for the kind words. Please make this request to your theme's author as there's nothing I can do on my end.
