### ISSUE TITLE
Performance Drop In Settings Menu

### ISSUE THREAD

**Issue by lukeycold** [mgmeyers/obsidian-style-settings#76]
I've noticed that whenever I open up the settings menu I get a really choppy experience while scrolling. I'm using Arch Linux and for a while I was using Manjaro. I'm not sure if this is a system specific issue or if it's something specific to the theme or possibly even my hardware. I have no performance drops at all in any other theme I have however. So I suspect that it's specific to the theme.

Note: Apologies if I'm using the GitHub issue system wrong. Still a little new to using it.

**Comment by mgmeyers** [comment]
@lukeycold I sounds like this is a theme issue? I would open an issue on the theme you are using rather than the style settings plugin

**Comment by lukeycold** [comment]
I'm so sorry! I seemed to open the issue in the wrong repo. I'm not sure how I got directed here since it's been a while. It might've been that I clicked the first GitHub link I could find that seemed remotely related to what I was having an issue with. Sorry about that!
