### ISSUE TITLE
FR: Open Style settings should open in a new Tab, not new Pane (0.16.)

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-style-settings#78]
I think with 0.16, opening directly in a new tab would be preferable?

<img width="739" alt="Pasted image 2022-08-31 07 42 32" src="https://user-images.githubusercontent.com/73286100/187601766-d00648c3-0db4-4dae-9442-e8ac769db44c.png">

**Comment by raisabelatrix** [comment]
YES PLEASE. It's so hard to see the changes with the modal in the way.

**Comment by ArtexJay** [comment]
Personally would prefer to have a toggle that would allow us to either open it in sidepanel (right/left) or tabs. I would prefer it opening in the sidebar as opposed to tabs like it does now.
