### ISSUE TITLE
Scroll bar settings won't stick

### ISSUE THREAD

**Issue by csss1234** [mgmeyers/obsidian-style-settings#79]
Obsidian .15.9
Blue Topaz 20220929
Style settings .4.11

https://user-images.githubusercontent.com/45954264/193435163-f31b15ae-4e76-4eaa-807a-58223a3bdab1.mov

**Comment by mgmeyers** [comment]
Hi @csss1234 Please file this as a bug in the blue topaz theme as I don't believe it is a style settings bug
