### ISSUE TITLE
Blockquote Font Style not changing anything

### ISSUE THREAD

**Issue by AaronM44** [mgmeyers/obsidian-style-settings#80]
Tried switching between normal, italic and oblique but the font style does not change. Tried changing the setting, then closing/reloading, tried disabling all other community add ons but still nothing changes.

All other Blockquote settings seem to work fine.

**Comment by mgmeyers** [comment]
Hi @AaronM44, This sounds like an issue with the theme you're using. I'd recommend opening an issue in the theme's github repository rather than here.
