### ISSUE TITLE
A function request about Minimal.

### ISSUE THREAD

**Issue by i-iooi-i** [mgmeyers/obsidian-style-settings#85]
![image](https://user-images.githubusercontent.com/1827701/196973210-6199c95c-9a88-476c-862e-fb234dc50ee8.png)

![image](https://user-images.githubusercontent.com/1827701/196974644-4efff312-75da-4d8a-a55a-5b57907f4ffc.png)

Hello, I'm using the Minimal theme.
I want to request a function, whether it is possible to add a switch to keep the color of the upper right corner area consistent with that of other areas.

![image](https://user-images.githubusercontent.com/1827701/196974331-37c22471-4fb2-4301-b3a7-be0c22a53b44.png)

Like this, it will look great. thank you~

**Comment by mgmeyers** [comment]
This seems like a request for the minimal theme. Please open an issue in the theme's repository rather than here
