### ISSUE TITLE
Heading divider lines overlap css callout boxes

### ISSUE THREAD

**Issue by train-con** [mgmeyers/obsidian-style-settings#86]
Hello, I love using your style settings for my obsidian vaults. I pair it up with minimal and css to make a sort of "wiki-esque" design.

There is a problem I've recently come across that hadn't been present before Obsidian updated to v1.0.0 where the callout boxes using [SIRvb's callout snippet](https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/Guide/Callouts.md) and the images in it are overlapped when I flip on the heading divider lines option.

I can provide pictures if needed. Thank you for your time.

**Comment by mgmeyers** [comment]
@train-con This seems like a theme issue rather than a style settings issue. You may want to report this to your theme's author
