### ISSUE TITLE
Is there a way to style "LISTS"?

### ISSUE THREAD

**Issue by omicreativedev** [mgmeyers/obsidian-style-settings#88]
I noticed that with obsidian lists (default theme) that all sublists are the same as the primary list. Is there a way (via css?) to change the sublist icons (to bullets for instance?) or subnumbers like: 1a, 1b, 1c

This is what it looks like now:

![Obsidian Lists](https://user-images.githubusercontent.com/82254764/201959663-a5b63f46-95ec-446d-bbc4-65f62aa4c481.jpg)

**Comment by mgmeyers** [comment]
@omicreativedev This seems unrelated to the Style Settings plugin. You may want to ask around in obsidian's discord or forum for help on this.
