### ISSUE TITLE
Scrolling within page preview breaks if "Seamless Embed" feature is turned ON

### ISSUE THREAD

**Issue by gabros20** [mgmeyers/obsidian-style-settings#9]
Hi, this issue was reported originally in obsidian-california-coast-theme repo.
https://github.com/mgmeyers/obsidian-california-coast-theme/issues/61

I came across the same problem while using "California Coast Obsidian Theme" and it seems the issue might be caused by the Style Settings plugin /  "Seamless Embed" feature.

If it's turned ON, scrolling within page preview will break. Turning it OFF fixes the problem.

**Feature turned ON**
![Screenshot 2021-04-08 at 15 37 31](https://user-images.githubusercontent.com/49348865/114036868-b8e23380-9880-11eb-8cbd-2f4464167565.jpg)

![Screenshot 2021-04-08 at 15 38 15](https://user-images.githubusercontent.com/49348865/114036855-b5e74300-9880-11eb-95ce-03eb17ab636b.jpg)

**Feature turned OFF**
![Screenshot 2021-04-08 at 15 50 53](https://user-images.githubusercontent.com/49348865/114038793-76215b00-9882-11eb-9199-0f7fded6b041.jpg)

![Screenshot 2021-04-08 at 15 51 28](https://user-images.githubusercontent.com/49348865/114038811-7ae60f00-9882-11eb-8fab-9ddab1f689cc.jpg)

**Comment by mgmeyers** [comment]
Thanks @gabros20! This is an issue with the theme rather than the plugin, so I'm going to close this issue here in favor of this one: https://github.com/mgmeyers/obsidian-california-coast-theme/issues/61
