### ISSUE TITLE
code syntax highlight is different in preview and read mode!

### ISSUE THREAD

**Issue by domeniczz** [mgmeyers/obsidian-style-settings#90]
Please make code syntax highlight be the same in preview mode and read mode

I have customize color in this plugin and some of the config item refer to different things in two modes

For example, in "Code and syntax highlight", for Java, "comment" refers to annotation like `@Component` in preview mode and refers to real comment like `// something` in preview mode

**Comment by domeniczz** [comment]
If my any extra info is needed, let me know

**Comment by mgmeyers** [comment]
This seems like a theme issue. Please report this to your theme's author
