### ISSUE TITLE
[Feature Request] Search in Style settings

### ISSUE THREAD

**Issue by Ravenightwing** [mgmeyers/obsidian-style-settings#93]
Sometimes themes have loads of setting options and are organized counterintuitively. It would be really nice to have a search option within style settings.

**Comment by trainbuffer** [comment]
While I am grateful for theme developers offering many setting options, it's sometimes hard to know where they've decided a setting belongs. This would be super helpful. ++

**Comment by mgmeyers** [comment]
This is now available in v 1.0.0 thanks to @mProjectsCode
