### ISSUE TITLE
Issues setting --font-ui-medium

### ISSUE THREAD

**Issue by PipeItToDevNull** [mgmeyers/obsidian-style-settings#94]
With style settings, is there a known deficiency where setting anything like `--font-ui-medium` directly or with another variable `--font-ui-medium: var(--pln-fnt-medium);` does not work well. You need to change the number in style settings off the default then back for the default to be rendered 

it seems the vanilla `--font-ui-medium` has precedence when Obsidian loads and is not being overwritten

**Comment by PipeItToDevNull** [comment]
The same occurs using `--h#-color`, the setting must be explicitly saved to become active and overcome the default variable

**Comment by mgmeyers** [comment]
@PipeItToDevNull Style settings does not apply any CSS variables unless the user has changed them from the defaults. It's up to the theme authors to explicitly set the defaults in CSS as they are defined in their style setting config.

Eg.

```
    - 
        id: h2-color
        title: H2 Color
        type: variable-themed-color
        format: hex
        opacity: false
        default-light: '#1f1f1f'
        default-dark: '#bababa'
```

also needs this to be set in the theme's CSS:

```
--h2-color: #1f1f1f;
```
