### ISSUE TITLE
Suggestion: Renaming a file, marking a text: How to better see the marking by default?

### ISSUE THREAD

**Issue by merlinuwe** [mgmeyers/obsidian-style-settings#95]
I'm using minimal theme in dark mode and I want to edit a filename. Is there a way to give the marked word more contrast _by default_?

I double clicked the word "Tinten" but I cannot really see the marking.

![image](https://user-images.githubusercontent.com/4138869/209404958-1f180426-436f-4ffb-acf1-be1c21650e8f.png)

I looked in style settings, and I found a way in Minimal --> Text --> Selected text background. 

![image](https://user-images.githubusercontent.com/4138869/209404727-871489c8-f0e4-4cd4-9ef6-d1d265fc406a.png)

![image](https://user-images.githubusercontent.com/4138869/209404785-2de92c73-c7ec-4004-a566-10a16bc344a9.png)

**Comment by mgmeyers** [comment]
@merlinuwe This seems to be an issue with the minimal theme. Please open an issue there instead
