### ISSUE TITLE
Suggestion: Option to hide (or fold) the code in "execute code settings"

### ISSUE THREAD

**Issue by merlinuwe** [mgmeyers/obsidian-style-settings#96]
I use the execute code plugin. It would be helpful, if the code could be hidden or folded, but the "run" and "clear" buttons must stay available to click them. So one can run a program but not always see the code.

At the upper left edge you see, how folding could be implemented:

![image](https://user-images.githubusercontent.com/4138869/209445176-ab73b980-a556-42b0-a51b-85eaff5179d2.png)

Some CSS snippet would also help.

**Comment by mgmeyers** [comment]
@merlinuwe This doesn't seem to be related to the style settings plugin. Try making this request in the execute code plugin repository.
