### ISSUE TITLE
Use strict embedding style globally is not working with Minimal Theme

### ISSUE THREAD

**Issue by brucvas** [mgmeyers/obsidian-style-settings#98]
Use strict embedding style globally is not working with Minimal Theme (the latest version). It does not remove the indentation/margin of the text of the paragraphs. 
Now it only works for title text.

![image](https://user-images.githubusercontent.com/88307063/210189564-6a5fcf59-e84b-4388-a7c9-eaa61a163cd6.png)

![image](https://user-images.githubusercontent.com/88307063/210189539-0c3ba227-6dc1-4474-a2b9-addb27fd3f68.png)

**Comment by mgmeyers** [comment]
Hi @brucvas this looks like an issue with the minimal theme. Please open an issue for the theme itself rather than here.
